#!/usr/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --mail-type=ALL
#SBATCH --mail-user=c.l.morales.ubal@tue.nl
#SBATCH --partition=mech.pf.q
#SBATCH --error=slurm-%j.err
#SBATCH --output=slurm-%j.out
#SBATCH --time=48:00:00

echo $PYTHONPATH
echo $PATH
pwd
cd /home/mech001/20215667/Tutorials/incompressible_flow/Inc_Species_Transport/4__optimization
/home/mech001/20215667/Adjoint_Design/gradient_validation
pwd
module purge
module load gcc/10.2.0
module load slurm/17.11.12
module use /cm/shared/modules/int/all
module load SciPy-bundle
module load openmpi/gcc/64/4.1.3

python ./optimization.py

